name: Build & push image

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Debug auth
        run: |
          echo "=== CREDS FILE ==="
          cat "${GOOGLE_GHA_CREDS_PATH:-$GOOGLE_APPLICATION_CREDENTIALS}" 2>&1 || true
          echo "=== gcloud auth print-access-token ==="
          gcloud auth print-access-token --verbosity=debug 2>&1 || true

      - name: Build & push image to Artifact Registry
        run: gcloud builds submit --tag "${REGION}-docker.pkg.dev/${PROJECT_ID}/interseguro-go-api/interseguro-go-api:latest" .
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGION: ${{ secrets.GCP_REGION }}
